# fly.toml app configuration file generated for az-stocker on 2024-11-08T10:31:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'az-stocker'
primary_region = 'phx'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[metrics]
port = 9091
path = "/metrics"

[[vm]]
size = 'shared-cpu-1x'
