{
 "title": "AZ Stocker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(stocker_http_client_cache[$__rate_interval])) by (cache_used)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stocker_http_client_cache) by (cache_used)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Program",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Rate by Program",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(stocker_program_requests[$__rate_interval])) by (program)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Programs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stocker_program_requests[$__rate_interval]) by (program)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Waters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Rate by Water",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(stocker_water_requests[$__rate_interval])) by (water)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waters",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stocker_water_requests[$__rate_interval]) by (water)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}